FROM node:lts-alpine3.14 as build
WORKDIR /dashy
COPY package*.json .
COPY yarn.lock .
ENV NODE_OPTIONS=--max_old_space_size=2048
RUN yarn install --registry=https://registry.yarnpkg.com/
RUN yarn
COPY . .
RUN yarn build

# Production Stage - Serve up built files with NGINX
FROM nginx:alpine as production
COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /dashy/dist /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]

